disabled_rules:
    - trailing_whitespace
    - force_cast
excluded:
    - Carthage
    - Pods
    - Source/Charts-master
    - Source/Pods
    - Charts-master
    - HikingTracker/Utilities/GPXParser.swift
    - Source/Utilites/GPXParser.swift
    - HikingTracker/Utilities/Solar.swift
    - Source/Utilities/Solar.swift



line_length: 200
    
